build_frontend:
  stage: build
  image: quay.io/podman/stable
  tags: [ docker]
  dependencies:
    - prepare
  before_script:
    - cat conf/registry.conf >> /etc/containers/registries.conf
    - podman login --tls-verify=false -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $REGISTRY
  script:
    - podman build -t $REGISTRY/ingestlistwrapper_frontend frontend/
    - podman push $REGISTRY/ingestlistwrapper_frontend
