include:
  - backend/.gitlab-ci.yml

stages:
  - lint
  - prep

prepare:
  image: alpine:3.22
  stage: prep
  tags: [ docker]
  script:
    # install tools we need to build our toolchain
    - apk add --no-cache git bash python3 py3-pip curl grep
    - chmod +x ./scripts/prepsrc.sh
    # run build script for download tool
    - bash ./scripts/prepsrc.sh
 
  
