backend-lint:
  variables:
    GOLANGCI_LINT_VERSION: '2.1.6'
  image: ${GITLAB_DEPENDENCY_PROXY}golangci/golangci-lint:v$GOLANGCI_LINT_VERSION
  tags: [ docker ]
  rules:
    - changes:
        - backend/**/*
    - exists:
        - '**/*.go'
  stage: lint
  script:
    # Write the code coverage report to gl-code-quality-report.json
    # and print linting issues to stdout in the format: path/to/file:line description
    # add `--issues-exit-code 0` to ignore linting issues
    - cd backend
    - golangci-lint run --output.text.path=stdout --output.text.colors=false --output.text.print-issued-lines=false --output.code-climate.path=gl-code-quality-report.json
  artifacts:
    reports:
      codequality: backend/gl-code-quality-report.json
    paths:
      - backend/gl-code-quality-report.json
  allow_failure: true

backend-prepare:
  image: alpine:3.22
  stage: build
  tags: [ docker]
  script:
    # install tools we need to build our toolchain
    - apk add --no-cache git bash python3 py3-pip curl grep
    - chmod +x ./scripts/prepsrc.sh
    # run build script for download tool
    - bash ./scripts/prepsrc.sh
  rules:
    - changes:
        - backend/**/*


include:
  - component: $CI_SERVER_FQDN/components/gitlab-ci-templates/podman-blha-build@1.1.9

backend-build:
  extends: .podman-blha-build
  variables:
    # Standard-Variablen für podman-build
    REGISTRY: "default-route-openshift-image-registry.apps.kubecluster.blha.mwfk.ad.lvnbb.de/dimag"
    BUILD_CONTEXT: "backend"
    IMAGE_TAG: "$REGISTRY/ingestlistwrapper_backend:${INGESTLIST_RELEASE}"
    IS_LATEST: "false"  # Kein :latest-Tag

    # Backend-spezifische Variablen
    INGESTLIST_RELEASE: "1.2.0"

    # Benutzerdefiniertes Skript (wird vor dem Build ausgeführt)
    BEFORE_BUILD_SCRIPT: |
      cp -R sources/ingestlist-${INGESTLIST_RELEASE}/ingestlist/ backend/third

  # Abhängigkeit zu backend-prepare
  needs: ["backend-prepare"]
