apiVersion: v1
kind: Secret
metadata:
  name: dev-postgres-secret
  namespace: dev
type: Opaque
stringData:
  POSTGRES_DB: ingestlist-wrapper
  POSTGRES_HOST_AUTH_METHOD: md5
  POSTGRES_PASSWORD: password
  POSTGRES_USER: ingestlistwrapper
