apiVersion: v1
data:
  config.yml: |-
    fileStoragePath: "/data"
    ingestListServer: "dev-ingestlist-service.dev.svc.cluster.local:21757"
    scheduler: "* * * * *"
    databaseConfig:
      host: dev-postgres-service.dev.svc.cluster.local 
      port: 5432
      user: ingestlistwrapper
      password: password
      dbname: ingestlist-wrapper
      sslmode: disable
kind: ConfigMap
metadata:
  annotations:
  name: ilwrapper-config
  namespace: dev
