---
name: Build App container

on: 
  push:
      branches: [main]
#      paths: [Dockerfile]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}

jobs:
  build-collection:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate image
        run : |
          echo "IMAGE_NAME=${REPO,,}" >>${GITHUB_ENV}

      - name: Login to container REGISTRY
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            types=ref,event=branch
            types=ref,event=tag
            types=raw,value=latest
            type=sha 

      - name: Build and push container image
        uses: docker/build-push-action@v5 
        with:
          context: .
          push: true
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
